# Generated by Django 5.0.6 on 2024-06-19 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('numero_identificacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a')], max_length=20)),
                ('tipo_documento', models.CharField(choices=[('Cc', 'Cedula de ciudadania'), ('Ce', 'Cedula de extrangeria'), ('Passpor', 'Pasaporte')], max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('P', 'Prefiero no decir')], max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_exp_documento', models.DateField()),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('nivel_riesgo', models.CharField(blank=True, choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5')], max_length=10, null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='photos')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dependiente.empresa')),
            ],
        ),
    ]
