# Generated by Django 5.0.6 on 2024-06-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependiente', '0002_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salud', models.FloatField(blank=True, null=True)),
                ('pension', models.FloatField(blank=True, null=True)),
                ('arl', models.FloatField(blank=True, null=True)),
                ('transporte', models.FloatField(blank=True, null=True)),
                ('salarioBase', models.FloatField(blank=True, null=True)),
                ('cajaCompensacion', models.FloatField(blank=True, null=True)),
                ('sena', models.FloatField(blank=True, null=True)),
                ('icbf', models.FloatField(blank=True, null=True)),
                ('cesantias', models.FloatField(blank=True, null=True)),
                ('interesCesantias', models.FloatField(blank=True, null=True)),
                ('vacaciones', models.FloatField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependiente.empleado')),
            ],
        ),
    ]
