# Generated by Django 4.2.6 on 2024-06-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorest', '0004_alter_independiente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independiente',
            name='fecha_exp_documento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='independiente',
            name='fecha_nacimiento',
            field=models.CharField(max_length=10),
        ),
    ]
