# Generated by Django 4.2.6 on 2024-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorest', '0007_alter_independiente_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independiente',
            name='imagen',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='photos'),
        ),
    ]
