# Generated by Django 4.2.6 on 2024-06-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorest', '0008_alter_independiente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independiente',
            name='fecha_exp_documento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='independiente',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='independiente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='independiente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
