# Generated by Django 4.2.6 on 2024-06-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorest', '0009_alter_independiente_fecha_exp_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='independiente',
            name='salairo_base',
            field=models.IntegerField(default=1300000),
        ),
    ]
