# Generated by Django 4.2.6 on 2024-06-24 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangorest', '0010_independiente_salairo_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCalculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salarioBase', models.FloatField(blank=True, null=True)),
                ('ibc', models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(40)])),
                ('salud', models.FloatField(default=12.5, max_length=50)),
                ('pension', models.FloatField(default=16, max_length=50)),
                ('arl', models.FloatField(blank=True, max_length=25, null=True)),
                ('CCF', models.FloatField(blank=True, max_length=25, null=True)),
                ('FSP', models.FloatField(blank=True, max_length=25, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangorest.independiente')),
            ],
        ),
        migrations.DeleteModel(
            name='Novedades',
        ),
    ]
