# Generated by Django 5.0.6 on 2024-06-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorest', '0011_datoscalculos_delete_novedades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independiente',
            name='salairo_base',
            field=models.FloatField(),
        ),
    ]
